name: Beerify CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - uses: actions/checkout@v4
      
      - uses: superfly/flyctl-actions/setup-flyctl@master

      # We need to install dependencies for the migrations.
      - name: Install dependencies
        run: |
          cd server
          npm install -g tsx
          npm install

      - name: Generate migrations
        run: |
          cd server
          npx drizzle-kit generate:pg

      - name: Push migrations
        run: |
          cd server
          npx tsx src/database/migrate.ts
      
      - name: Deploy to fly.io
        run: 
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
