name: Beerify CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Build frontend
      run: |
        cd client
        npm install
        npm run build

    - name: Copy frontend build to backend
      run: |
        mkdir -p server/dist
        cp -r client/dist/* server/dist/

    - name: Build backend
      run: |
        cd server
        npm install
        npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: ./server/dist/
  

  deploy:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    needs: build
    if: needs.build.result == 'success' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
      
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: ./server/dist/

      # We need to install drizzle-orm, drizzle-kit and tsx so that we can run the migrations
      - name: Install tsx
        run: |
          npm install drizzle-orm@0.30.8
          npm install -D tsx
          npm install -D drizzle-kit@0.20.14

      - name: Generate migrations
        run: |
          cd server
          npx drizzle-kit generate:pg

      - name: Push migrations
        run: |
          cd server
          npx tsx database/migrate.ts
        
      
      - name: Deploy to fly.io
        run: |
          cd server
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
